### ISSUE TITLE
Proposal to move project docker-coq-action to coq-community

### ISSUE THREAD

**Issue by erikmd** [coq-community/manifesto#101]
**Project name:** docker-coq-action

**Initial author(s):** @erikmd, @Zimmi48

**Current URL:** https://github.com/erikmd/docker-coq-action

**Kind:** GitHub Action compatible with Docker-Coq

**License:** MIT

**Description:**

This repo provides a GitHub container action, that can be used together with `coqorg/coq` images.

Typical use:

```yml
strategy:
  matrix:
    coq_version:
      - 8.11
      - dev
    ocaml_version: ['4.07-flambda']
steps:
- uses: actions/checkout@v2
- uses: erikmd/docker-coq-action@master
  with:
    opam_file: 'folder/coq-proj.opam'
    coq_version: ${{ matrix.coq_version }}
    ocaml_version: ${{ matrix.ocaml_version }}
```

For more details, see the [README](https://github.com/erikmd/docker-coq-action#readme) or the accompanying [demo](https://github.com/erikmd/docker-coq-github-action-demo).

**Status:** maintained by @erikmd
