### ISSUE TITLE
Add deploy job to CI to publish new releases when tag is put.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#49]
## Meta-issue ##

The idea is simply to make it as easy as possible for principal maintainers of coq-community packages to publish a new release.

When pushing a new tag, the deploy job would:
- create a release on GitHub, include information about the supported versions of Coq and dependencies;
- create a PR on the Coq opam repository using opam-publish or an ad-hoc script;
- (optional / later) create a PR on the nixpkgs repository, updating the package in `coqPackages`.

A question is how to include the release date meta-data in the opam file that is published in the opam repository. Either the maintainer updates the date in `meta.yml` before tagging (but I expect people to forget), or we add it later (but then we can't use opam-publish as-is).

**Comment by ejgallego** [comment]
Note that `topkg` / `dune-release` already can do a lot of this workflow; so indeed you may want to start from there [and hope an eventual integration when all the pieces fall together]

**Comment by Zimmi48** [comment]
Thanks for the info. I hadn't realized `dune-release` was so powerful. Then, it makes sense to just wait on Dune support for Coq, migrate the coq-community packages, and document the process using dune-release.

**Comment by ejgallego** [comment]
`dune-release` is just a fork of `topkg` which is indeed way more powerful [but it indeed allows more flexiblity]. In fact, I find `dune-release` a bit limited [for example they removed options to target a different opam repos, so indeed there is work to do here; but the base model `topkg bistro` seems a good starting point.

**Comment by Zimmi48** [comment]
OK, thanks for the additional info. So either we propose changes to `dune-release`, or we try something on top of `topkg`.

**Comment by ejgallego** [comment]
Note that https://github.com/ejgallego/coq-plugin-template includes reasonable support for using `dune-release`

**Comment by palmskog** [comment]
@gares might have some hints for us since he recently automated a similar workflow opening a PR for Elpi, see [example](https://github.com/coq/opam/pull/2702), and also [this Coq Zulip topic](https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs-.26-users/topic/Release.20automation.20for.20more.20projects).

**Comment by gares** [comment]
We looked into dune-release (I use it for elpi for example), but it seems it does not work for vscoq since the opam package (and dune project) are in a subdirectory: https://github.com/tarides/dune-release/issues/471 Also I did not find any use of it in CI.

Then we looked into opam-release which does fewer things and we paired it with a simple action to build a tarball an create a draft release. With some hacks one can convince opam-release to run in batch mode and open a PR.

So we used it in vscoq, and then I reproduced it in coq-elpi (which is not even a dune project, so it can't use dune-release to begin with). In vscoq @maximedenes did separate the job into two jobs which always run but don't really do the action in the very end, to keep the CI code tested. I did not do it in coq-elpi. I'll let you chose if the extra CI minutes are worth it in the context of coq-community.

Here my job for coq-elpi:
https://github.com/LPCIC/coq-elpi/blob/dfe528598d04588376eb6b240003647cdd5aa473/.github/workflows/main.yml#L40-L94
```yaml
release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
```
of course you want to run this only if the CI was run on a tag

```yaml
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Create archive
        run: |
          VERSION="${GITHUB_REF_NAME_SLUG#v}"
          git archive -o coq-elpi-$VERSION.tar.gz --prefix=coq-elpi-$VERSION/ $GITHUB_SHA .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: coq-elpi-*.tar.gz
          fail_on_unmatched_files: true
          prerelease: true
          generate_release_notes: true
          name: Coq-Elpi ${{ github.ref }} for Coq XXX
```
Since my tags are named like `v1.18.0` I compute the `VERSION` (without the `v`).
The slug thing also takes care of other symbols git does not like, I just copied what @maxime did, no strong opinion.
Here I create a pre-release with the artifact tarball. I guess for dune projects one needs to also call `dune subst` (I guess dune release does it for you) so that the version string in the archive is correct (and not `%VERSION%`).
The release is marked as a pre-prelease, and the title is a stub (I like to put there the Coq version but it is not immediately inferrable so I just left a XXX placeholder.

And here the dragons:
```yaml
      - name: Use OCaml 4.14.x
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          opam-local-packages: |
            !coq-elpi.opam
```
You need ocaml for opam-release. The action also tries to install the dependencies of the opam files at the root (which is useless, and also may require non stradard opam repos) and miraculously does not look into subfolders (so vscoq CI job does not need the last option). 

```yaml
      - name: Write PAT
        env:
          OPAM_PUBLISH_TOKEN: ${{ secrets.OPAM_PUBLISH_TOKEN }}
        run: |
          mkdir -p ~/.opam/plugins/opam-publish
          printf "$OPAM_PUBLISH_TOKEN" > ~/.opam/plugins/opam-publish/coqelpibot.token
```
You need to issue an access tokem from the bot account (just google for PAT), take an old token format otherwise the new ones always expire in at most 1 year, put it into a secret, then "preseed" opam-publish configuration.
If you run it by hand, it asks you the token interactively, then it stores it there to avoid asking you again.
Credit to @erikmd for hacking this, I believe.

```yaml          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_KEY }}
```         
The bot needs an ssh key, the private part is stored in this secret, the action does the rest.
Now you can push to the github repo of the bot (to his fork of coq/opam). 

```yaml
      - name: Install opam-publish # 2.0.3 because more recent versions do not respect OPAMYES
        run: opam install -y -j 2 opam-publish=2.0.3
```
Why would it work out of the box?

```yaml
      - name: Publish
        run: |
          eval $(opam env)
          git config --global user.name coqelpibot
          git config --global user.email coqelpibot@inria.fr
          OPAM_SUITE=released
          TAG=`git tag --sort=-v:refname|head -1`
          opam-publish --tag=$TAG --packages-directory=$OPAM_SUITE/packages --repo=coq/opam --no-browser -v ${TAG##v}	https://github.com/LPCIC/coq-elpi/releases/download/$TAG/coq-elpi-${TAG##v}.tar.gz
```
You want to prepare a commit for coq/opam, the author is the bot.
Here I use old code of mine to get the tag name, I think I should have use the `github.ref` above.
Then the URL must match the one of the artifact attached to the pre-release above.
